replicas: 1
clusterHealthCheckParams: "local=true"
ingress:
  enabled: true
  hosts:
    - host: centralized-logging-es.test.paas.onemrva.priv
      paths:
        - path: /
resources:
  requests:
    cpu: "1000m"
    memory: "4Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"
