daemonset:
  extraEnvs: 
    - name: ELASTICSEARCH_HOSTS
      value: "http://elasticsearch-master:9200"
deployment:
    extraEnvs: 
    - name: ELASTICSEARCH_HOSTS
      value: "http://elasticsearch-master:9200"