apiVersion: v1
kind: Service
metadata:
  name: {{ include "elastichq.fullname" . }}
  labels:
    {{- include "elastichq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "elastichq.selectorLabels" . | nindent 4 }}
