version: 2

plan:
  project-key: PAAS
  key: PAASLOGS
  name: Centralized Logging

stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Build Project
Build Project:
  tasks:
    - checkout:
        repository: PAAS - centralized-logging
        force-clean-build: 'true'
    - checkout:
        repository: Master - ARCHI - bamboo
        path: scripts
        force-clean-build: 'false'
    - script:
        interpreter: SHELL
        scripts:
          - set -e
          - source scripts/tools/toolsrc
          - tools__init_path && tools__init_proxy && tools__init_docker_ci && tools__helm_add_onemrva_repo
          - sh deploy.sh onemrva
          - helm package elastichq/ --version "0.${bamboo.buildNumber}.0"
          - curl --fail -u "${bamboo_nexus_user}:${bamboo_nexus_secret}" "${bamboo.helm_repository_url}" --upload-file "elastichq-${bamboo.buildNumber}.tgz"
variables: {}
notifications: []
labels: []
other:
  concurrent-build-plugin: system-default